### ISSUE TITLE
Is there a version that supports iPhone 6S?

### ISSUE THREAD

**Issue by jhzou1** [AidanGamzer/ReRa1n#14]
We hope that the author can release the version that supports the downgrading of iphone6s ios14 to ios9 or ios10, which is really helpful

**Comment by dupeiduo** [comment]
I am waiting for it.

**Comment by jhzou1** [comment]
> I am waiting for it.

Any news?my friend?

**Comment by AidanGamzer** [comment]
Project is discontinued until further notice.
