### ISSUE TITLE
Stuck after enter device password

### ISSUE THREAD

**Issue by Spec122** [AidanGamzer/ReRa1n#2]
When i run rera1n.sh i get some errors
`aclocal: warning: couldn't open directory 'm4': No such file or directory   `
`checking whether we need platform-specific build settings... ./configure: line 16616: syntax error near unexpected token `openssl,'                                                                                                             ./configure: line 16616: `PKG_CHECK_MODULES(openssl, $OPENSSL_REQUIRES_STR, have_openssl=yes, have_openssl=no)'         make: *** No targets specified and no makefile found.  Stop.                                                            make: *** No rule to make target 'install'.  Stop.         `

And when i run it again, pick "USB"
`[*] Welcome to ReRa1n                                                                                                   [*] Checking for dependencies                                                                                           [*] Dependencies found!                                                                                                 [*] SSH over WiFi, USB or NONE (CaSeSeNsItIvE): USB                                                                     [*] You chose USB.                                                                                                      [*] USB selected.                                                                                                       [*] Open a second terminal window and enter: cd rerain-dep && sudo ./forward.sh                                         [*] Press enter to continue:                                                                                            [*] Enter the root password of your iDevice: 111111`
Script just stack
How i can fix it?

UPD:
full log https://gist.github.com/Spec122/c6dca21197d5c1949b8b26977369da64

OS: Ubuntu 16.04 (WSL)

**Comment by AidanGamzer** [comment]
Run this: sudo apt-get install libgcrypt20-doc gnutls-doc gnutls-bin usbmuxd git libplist-dev libplist++ python2.7-dev python3-dev libusbmuxd4 libreadline6-dev make libusb-dev openssl libimobiledevice-dev libzip-dev libcurl4-openssl-dev libssl-dev sshpass
Then sudo ldconfig
then delete rerain-dep
then rerun :)

**Comment by Spec122** [comment]
> Run this: sudo apt-get install libgcrypt20-doc gnutls-doc gnutls-bin usbmuxd git libplist-dev libplist++ python2.7-dev python3-dev libusbmuxd4 libreadline6-dev make libusb-dev openssl libimobiledevice-dev libzip-dev libcurl4-openssl-dev libssl-dev sshpass
> Then sudo ldconfig
> then delete rerain-dep
> then rerun :)


Thanks, it really worked for me
