### ISSUE TITLE
I'm blocked "You can now start rera1n.sh"

### ISSUE THREAD

**Issue by 72y9op** [AidanGamzer/ReRa1n#3]
`./rera1n.sh
[*] Welcome to ReRa1n
[*] Checking for dependencies
[*] Do you want to install dependencies manually or have the script do it for you? (M/A) m
[-] Dependencies not found
[*] Installing dependencies
[*] Checking Package Manager
DEBIAN SYSTEMS ONLY
FOR OTHER PLATFORMS, SEE README.MD

Starting in 10 seconds. Press ctrl-C to cancel.
[*] Package manager supported (apt)
[*] Creating deps directory
mkdir: impossible de créer le répertoire « rerain-deps »: Le fichier existe
[*] Starting apt... please input root password.
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Note : sélection de libplist3 pour l'expression rationnelle « libplist+ »
Note : sélection de libplist-dev pour l'expression rationnelle « libplist+ »
Note : sélection de libplist-doc pour l'expression rationnelle « libplist+ »
Note : sélection de libplist++-dev pour l'expression rationnelle « libplist+ »
Note : sélection de libplist-utils pour l'expression rationnelle « libplist+ »
Note : sélection de libplist++3v5 pour l'expression rationnelle « libplist+ »
Note : sélection de « libreadline-dev » au lieu de « libreadline6-dev »
git est déjà la version la plus récente (1:2.24.0-1).
gnutls-bin est déjà la version la plus récente (3.6.10-5).
gnutls-doc est déjà la version la plus récente (3.6.10-5).
libcurl4-openssl-dev est déjà la version la plus récente (7.66.0-1+b1).
libgcrypt20-doc est déjà la version la plus récente (1.8.5-3).
libimobiledevice-dev est déjà la version la plus récente (1.2.1~git20181030.92c5462-1).
libplist++-dev est déjà la version la plus récente (2.0.1~git20190104.3f96731-1).
libplist++3v5 est déjà la version la plus récente (2.0.1~git20190104.3f96731-1).
libplist-dev est déjà la version la plus récente (2.0.1~git20190104.3f96731-1).
libplist-doc est déjà la version la plus récente (2.0.1~git20190104.3f96731-1).
libplist-utils est déjà la version la plus récente (2.0.1~git20190104.3f96731-1).
libplist3 est déjà la version la plus récente (2.0.1~git20190104.3f96731-1).
libreadline-dev est déjà la version la plus récente (8.0-3).
libssl-dev est déjà la version la plus récente (1.1.1d-2).
libusb-dev est déjà la version la plus récente (2:0.1.12-32).
libusbmuxd4 est déjà la version la plus récente (1.1.0~git20190924.b097ea3-2).
libzip-dev est déjà la version la plus récente (1.5.1-4).
make est déjà la version la plus récente (4.2.1-1.2).
openssl est déjà la version la plus récente (1.1.1d-2).
python2.7-dev est déjà la version la plus récente (2.7.17-1).
python3-dev est déjà la version la plus récente (3.7.5-1).
sshpass est déjà la version la plus récente (1.06-1+b1).
usbmuxd est déjà la version la plus récente (1.1.1~git20181007.f838cf6-1+b1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 1654 non mis à jour.
[*] Cloning repositories required to run
fatal: le chemin de destination 'libplist' existe déjà et n'est pas un répertoire vide.
fatal: le chemin de destination 'libusbmuxd' existe déjà et n'est pas un répertoire vide.
fatal: le chemin de destination 'iphonessh' existe déjà et n'est pas un répertoire vide.
fatal: le chemin de destination 'not-secret-secret' existe déjà et n'est pas un répertoire vide.
fatal: le chemin de destination 'libimobiledevice' existe déjà et n'est pas un répertoire vide.
fatal: le chemin de destination 'libirecovery' existe déjà et n'est pas un répertoire vide.
fatal: le chemin de destination 'idevicerestore' existe déjà et n'est pas un répertoire vide.
fatal: le chemin de destination 'libgeneral' existe déjà et n'est pas un répertoire vide.
fatal: le chemin de destination 'img4tool' existe déjà et n'est pas un répertoire vide.

[*] Installing libplist
autogen.sh: 12: autogen.sh: libtoolize: not found
autogen.sh: 14: autogen.sh: aclocal: not found
autogen.sh: 15: autogen.sh: autoheader: not found
autogen.sh: 16: autogen.sh: automake: not found
autogen.sh: 17: autogen.sh: autoconf: not found
autogen.sh: 21: autogen.sh: ./configure: not found
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
make: *** Aucune règle pour fabriquer la cible « install ». Arrêt.

[*] Installing libusbmuxd
autogen.sh: 6: autogen.sh: libtoolize: not found
autogen.sh: 8: autogen.sh: aclocal: not found
autogen.sh: 9: autogen.sh: autoheader: not found
autogen.sh: 10: autogen.sh: automake: not found
autogen.sh: 11: autogen.sh: autoconf: not found
autogen.sh: 14: autogen.sh: ./configure: not found
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
make: *** Aucune règle pour fabriquer la cible « install ». Arrêt.

[*] Installing USB SSH Deps

[*] Installing forwarder script for USB SSH
cp: impossible d'évaluer './forwarder.sh': Aucun fichier ou dossier de ce type

[*] Installing libirecovery
./autogen.sh: 12: ./autogen.sh: libtoolize: not found
./autogen.sh: 14: ./autogen.sh: aclocal: not found
./autogen.sh: 15: ./autogen.sh: autoheader: not found
./autogen.sh: 16: ./autogen.sh: automake: not found
./autogen.sh: 17: ./autogen.sh: autoconf: not found
./autogen.sh: 21: ./autogen.sh: ./configure: not found
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
make: *** Aucune règle pour fabriquer la cible « install ». Arrêt.

[*] Installing idevicerestore
./autogen.sh: 12: ./autogen.sh: libtoolize: not found
./autogen.sh: 14: ./autogen.sh: aclocal: not found
./autogen.sh: 15: ./autogen.sh: autoheader: not found
./autogen.sh: 16: ./autogen.sh: automake: not found
./autogen.sh: 17: ./autogen.sh: autoconf: not found
./autogen.sh: 21: ./autogen.sh: ./configure: not found
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
make: *** Aucune règle pour fabriquer la cible « install ». Arrêt.

[*] Installing libgeneral
./autogen.sh: ligne 3: aclocal : commande introuvable
./autogen.sh: ligne 4: autoconf : commande introuvable
./autogen.sh: ligne 5: autoheader : commande introuvable
./autogen.sh: ligne 6: automake : commande introuvable
./autogen.sh: ligne 7: autoreconf : commande introuvable
./autogen.sh: ligne 8: ./configure: Aucun fichier ou dossier de ce type
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
make: *** Aucune règle pour fabriquer la cible « install ». Arrêt.

[*] Installing img4tool
./autogen.sh: ligne 3: aclocal : commande introuvable
./autogen.sh: ligne 4: autoconf : commande introuvable
./autogen.sh: ligne 5: autoheader : commande introuvable
./autogen.sh: ligne 6: automake : commande introuvable
./autogen.sh: ligne 7: autoreconf : commande introuvable
./autogen.sh: ligne 8: ./configure: Aucun fichier ou dossier de ce type
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
make: *** Aucune règle pour fabriquer la cible « install ». Arrêt.
[*] Dependencies installed
[*] You can now start rera1n.sh
`
Loop and loop and loop...

**Comment by 72y9op** [comment]
I have found ! Copy Install and rera1n inside "rerain-deps" start rerain.sh and it's good

**Comment by 72y9op** [comment]
Ok no, it's not this

**Comment by StupidCodes** [comment]
help please, same issue

**Comment by A-Pringle-Can** [comment]
I typed:   sudo ./install.sh
i think that was the solution because mine is now working after I did that

**Comment by AidanGamzer** [comment]
Working on this, will be fixed in the next or second next update :)

**Comment by AidanGamzer** [comment]
Fixed, will push update tonight :smile:
