### ISSUE TITLE
./rera1n.sh: line 197: cd: rerain-dep: No such file or directory

### ISSUE THREAD

**Issue by Chintu91** [AidanGamzer/ReRa1n#4]
i got error after type usb
root@kali:~/ReRa1n# ./rera1n.sh
[*] Welcome to ReRa1n
[*] Checking for dependencies
[*] Do you want to install dependencies manually or have the script do it for you? (M/A) M
[*] Manual installation guide available on the github repository under MANUAL.md
[*] SSH over WiFi, USB or NONE (CaSeSeNsItIvE): USB
[*] You chose USB.
[*] USB selected.
./rera1n.sh: line 197: cd: rerain-dep: No such file or directory
[*] Open a second terminal window and enter: cd /usr/bin sudo fordward.sh 
[*] Press enter to continue:

**Comment by AidanGamzer** [comment]
You have not installed the dependencies. 
You selected manual (M) installation, but evidently did not install the dependencies by running ./install.sh in the cloned repository.
