### ISSUE TITLE
Recommendation: Make sure distro packages libimobiledevice-utils libimobiledevice-dev are NOT installed when running this script.

### ISSUE THREAD

**Issue by nightness** [AidanGamzer/ReRa1n#9]
In writing [my own install script](https://github.com/nightness/libimobiledevice-installer), to just handle building and installing idevicerestore, I found it more than helpful to make sure they don't have distro packages libimobiledevice-utils and libimobiledevice-dev installed.

sudo apt-get remove libimobiledevice-utils libimobiledevice-dev

**Comment by tongtongzhe** [comment]
Prompt fordward.sh not found. I ran rera1n with some other commands, but I can only brush the open authentication version of Apple server, I don't know if it's an operation error.

**Comment by xzjohy** [comment]
> Prompt fordward.sh not found. I ran rera1n with some other commands, but I can only brush the open authentication version of Apple server, I don't know if it's an operation error.


You don't have to do what he says. And there’s a error here that fordward.sh should be forward.sh

**Comment by aditmac1** [comment]
> > Prompt fordward.sh not found. I ran rera1n with some other commands, but I can only brush the open authentication version of Apple server, I don't know if it's an operation error.
> 
> You don't have to do what he says. And there’s a error here that fordward.sh should be forward.sh

I have same issue, is it because I'm using Parallel Desktop?

**Comment by aditmac1** [comment]
> > > Prompt fordward.sh not found. I ran rera1n with some other commands, but I can only brush the open authentication version of Apple server, I don't know if it's an operation error.
> > 
> > 
> > You don't have to do what he says. And there’s a error here that fordward.sh should be forward.sh
> 
> I have same issue, is it because I'm using Parallel Desktop?

I'm running on Debian GNU Linux 9

**Comment by AidanGamzer** [comment]
Project is discontinued until further notice.
